#!/bin/sh -e

DBDIR=.ntdedup

HASH_CMD=sha1sum

mkdir -p "$DBDIR"

ntdedup_hash() {
    ${HASH_CMD} "$1" | cut -d ' ' -f 1
}

ntdedup_inode() {
    ls -i "$1" | cut -d ' ' -f 1
}

ntdedup_run() {
    find -type f | (
        while read -r file; do
            hash=`ntdedup_hash "$file"`
            hashfile="$DBDIR/$hash"
            if [ -e "$hashfile" ]; then
                i_file=`ntdedup_inode "$file"`
                i_hash=`ntdedup_inode "$hashfile"`
                # check if inodes already match
                if [ "$i_file" != "$i_hash" ]; then
                    # verify contents
                    if cmp "$hashfile" "$file"; then
                        ln -vf "$hashfile" "$file";
                    else
                        # This is extremely unlikely and we give up
                        >&2 echo "HASH COLLISION: $file"
                        exit 1
                    fi
                fi
            else
                # add to the hashed database
                ln "$file" "$hashfile"
            fi
        done
    )
}

ntdedup_check () {
    if [ -e "$DBDIR" ] ; then
        find "$DBDIR" -type f | (
        while read -r file; do
            hash=`basename "$file"`
            rehash=`ntdedup_hash "$file"`
            if [ "$hash" != "$rehash" ]; then
                >&2 echo "FAILED: $file"
            fi
        done
        )
    fi
}

case "$1" in
    run)
        ntdedup_run
        ;;
    check)
        ntdedup_check
        ;;
    *)
        >&2 echo "Unknown command"
        ;;
esac
